# A Python script for making subdirectories for running the code.
# IMPORTANT: This script should be run from the root directory of the project.

#------------------- Description -------------------#

# In analogy to a tissue sample, each "sample" is a unique initial configuration of cells.
# Along with the initial configuration, we also provide configuration parameters
# that will determine how this sample evolves in time, 
# and when we want logs or output vtk files.

# Accordingly, each subdirectory under the samples/ directory 
# will contain the following things:

# 1. A file called sample.topo (currently generated from scripts/tvm/sphere1.py)
#       -> this is the initial configuration of cells, generated using a voronoi tessellation
 
# 2. A file called conf, which contains the configuration parameters for the sample.
#       -> this file is generated by this script, specifically the makeConfFile() function

# 3. PENDING: A shell script called run.sh, which is basically a shortcut 
#   to run the tvm executable from "build/", using the initial configuration and parameters
#   set up in this subdirectory.


# ------------------- Directory Structure -------------------#

# IN this script all runs are contained in the samples/ directory.
# samples/ is included in .gitignore, so if you change this, 
# please modify gitignore accordingly.
# subdirectories can be named in a systematic way, e.g.
# if you want to make 10 runs with s0 = 5.2 , you can name the subdirectories
# 5.2_0, 5.2_1, ... 5.2_9

import os
# import glob
# import numpy as np

# This function creates a conf file in the input directory "dir"
# with the given parameters.
# The intended use is within the makeSamplesSubDir() function.
def makeConfFile(s0 = 5.7, dir = "samples/"):
    initTime = 0
    finalTime = 2000
    eulerStep = 0.005
    dumpTime = 100
    logTime = 10
    Lth = 0.02
    T = 1e-4
    kv = 1
    xRange = 8
    yRange = 8
    zRange = 8
    xPeriodicity = "p"
    yPeriodicity = "p"
    zPeriodicity = "p"
    confContent = ""
    # Initial time, final time, Euler step
    confContent += "time {} {} {}\n".format(initTime, finalTime, eulerStep)
    # Dump vtk interval
    confContent += "dump vtk {:d}\n".format(dumpTime)
    # Log interval
    confContent += "log {:d}\n".format(logTime)
    # Target shape index and gamma
    confContent += "s0 {}\n".format(s0)
    # Thermal length
    confContent += "Lth {}\n".format(Lth)
    # Temperature 
    confContent += "T {:.0e}\n".format(T)
    # Volume Stiffness
    confContent += "kv {}\n".format(kv)
    # Box size
    confContent += "box {} {} {} {} {} {}\n".format(
        xRange, yRange, zRange, xPeriodicity, yPeriodicity, zPeriodicity)
    # Write to file. First, if a conf file 
    # already exists in this directory, delete it before making a new one.
    if os.path.isfile(dir + "conf"):
        os.remove(dir + "conf")
    with open(dir + "conf", "w") as f:
        f.write(confContent)
        f.close()
    return

# This function creates and populates a subdirectory in the input directory "dir"
# with a conf file and an initial configuration file called sample.topo.

# The intended use is to create a subdirectory for each run of the code in the samples/ directory.

def makeSamplesSubDir(s0:float = 5.2,
                      dir:str = "samples/"):

    # It is important to ensure then that "dir" is a string that ends with "/"
    if not dir.endswith("/"):
        raise ValueError("The input directory should end with a '/'.") 
    
    # First, check if the directory already exists.
    if os.path.isdir(dir):
        print("Directory {} already exists.".format(dir))
        return
    else:
        # Create the subdirectory
        os.mkdir(dir)
        # Make a conf file in this subdirectory.
        makeConfFile(s0, dir)
        currentDir = os.getcwd()
        # Run the scripts/tvm/sphere1.py script to create a sample.topo in the directory.
        sampleScriptFile = currentDir + "/scripts/tvm/main.py"
        os.system("cd {} && python3 {}".format(dir, sampleScriptFile))
        # Now, make a run.sh file in this directory.
        # with open(dir + "run.sh", "w") as f:
        #     f.write("#!/bin/bash\n")
        #     f.close()
        # # Make the run.sh file executable
        # os.system("chmod +x {}run.sh".format(dir))
        return

def main():
    # create the directory "samples/" if it doesnt exist
    if not os.path.isdir("samples/"):
        os.mkdir("samples/")
    # probability = 0.8
    # if not os.path.isdir("samples/p_{}/".format(probability)):
    #     os.mkdir("samples/p_{}/".format(probability))

    # now make subdirectories for the runs
    s0 = 5.2
    runID = 1
    makeSamplesSubDir(
        s0 = s0,
        # dir = "samples/{}_{}/".format(s0,runID))
        dir = "test/")
    return

if __name__ == "__main__":
    main()
