executable      = /home/mameen/examples/singularity_wrapper.sh
arguments       = /home/mameen/examples/ubuntu18_povray_paula.img run_job.sh

transfer_input_files = multiple_patterns.py, setup.py, toolbox, run_job.sh
should_transfer_files = YES

output          = multiple_patterns_2_cells/test/job.out
error           = multiple_patterns_2_cells/test/job.err
log             = multiple_patterns_2_cells/test/job.log

request_cpus    = 1
request_memory  = 4 GB

queue