executable = /home/mameen/examples/singularity_wrapper.sh
arguments  = /home/mameen/examples/ubuntu18_povray_paula.img /home/mameen/sp_5_cell_increase/run_13/run_job.sh
transfer_input_files = /home/mameen/sp_5_cell_increase.py, /home/mameen/setup.py, /home/mameen/toolbox 
should_transfer_files = YES
output     = output.txt
error      = error.txt
log        = log.txt
getenv     = True
request_cpus = 1
request_memory = 1 GB
Requirements = TARGET.vm_name == "its-u20-nfs-20210413" && regexp("CRUSH", TARGET.name)
queue 
